/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface */

#ifndef _Included_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
#define _Included_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_opensslDynamicallyLoaded
#define com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_opensslDynamicallyLoaded 1L
/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    getLibraryBuildDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_getLibraryBuildDate
  (JNIEnv *, jclass);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    initializeOpenSSL
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_initializeOpenSSL
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CTX_getValue
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CTX_1getValue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    getByteBufferPointer
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_getByteBufferPointer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    RAND_nextBytes
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_RAND_1nextBytes
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    RAND_setSeed
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_RAND_1setSeed
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_create
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1create
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_init
 * Signature: (JJII[B[B)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1init
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_getBlockSize
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1getBlockSize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_getKeyLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1getKeyLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_getIVLength
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1getIVLength
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_encryptUpdate
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1encryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_decryptUpdate
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1decryptUpdate
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_encryptFinal
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1encryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_decryptFinal
 * Signature: (JJ[BII[BIZ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1decryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CIPHER_delete
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CIPHER_1delete
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    GCM_init
 * Signature: (JJI[B[BI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_GCM_1init
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    GCM_update
 * Signature: (JJI[BII[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_GCM_1update
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    GCM_encryptFinal
 * Signature: (JJ[BII[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_GCM_1encryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    GCM_decryptFinal
 * Signature: (JJ[BII[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_GCM_1decryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CCM_init
 * Signature: (JJI[B[BI)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CCM_1init
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CCM_update
 * Signature: (JJI[BII[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CCM_1update
  (JNIEnv *, jclass, jlong, jlong, jint, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CCM_encryptFinal
 * Signature: (JJ[BII[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CCM_1encryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    CCM_decryptFinal
 * Signature: (JJ[BII[BI[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_CCM_1decryptFinal
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint, jint, jbyteArray, jint, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_create
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1create
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_copy
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1copy
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_update
 * Signature: (IJ[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1update
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_digest
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1digest
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_digest_and_reset
 * Signature: (IJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1digest_1and_1reset
  (JNIEnv *, jclass, jint, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_size
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_reset
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1reset
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    DIGEST_delete
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_DIGEST_1delete
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_create
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1create
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_init
 * Signature: (IJ[BI)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1init
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_update
 * Signature: (IJ[BII)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1update
  (JNIEnv *, jclass, jint, jlong, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_doFinal
 * Signature: (IJ[B)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1doFinal
  (JNIEnv *, jclass, jint, jlong, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_size
 * Signature: (IJ)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1size
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_reset
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1reset
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HMAC_delete
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HMAC_1delete
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    PBKDF2_derive
 * Signature: (ILjava/lang/String;[B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_PBKDF2_1derive
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HKDF_extract
 * Signature: (ILjava/lang/String;[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HKDF_1extract
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jbyteArray);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HKDF_expand
 * Signature: (ILjava/lang/String;[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HKDF_1expand
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    HKDF_derive
 * Signature: (ILjava/lang/String;[B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_HKDF_1derive
  (JNIEnv *, jclass, jint, jstring, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    KEYWRAP_wrap
 * Signature: (I[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_KEYWRAP_1wrap
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface
 * Method:    KEYWRAP_unwrap
 * Signature: (I[B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ibm_crypto_plus_provider_openssl_OpenSSLNativeInterface_KEYWRAP_1unwrap
  (JNIEnv *, jclass, jint, jbyteArray, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
